import type { Metadata } from "next";
import { ContactBand, PageHero, SiteFooter, SiteHeader } from "../site-components";
import { standards } from "../site-data";

export const metadata: Metadata = { title: "About DAASK Build Ltd", description: "Meet a Donegal building contractor backed by 25 years of construction and project-management experience." };

export default function AboutPage() {
  return <main><SiteHeader /><PageHero eyebrow="About DAASK Build" title="Experience, accountability and care." lead="A registered and fully insured building contractor serving Ballyshannon, Donegal and surrounding areas." /><section className="story section"><div><p className="eyebrow dark"><span /> Our approach</p><h2>Engineering thinking. Hands-on delivery.</h2></div><div className="story-copy"><p>DAASK Build Ltd brings together 25 years of construction and project-management experience. We understand that successful projects depend on more than workmanship alone: good planning, sequencing, communication and responsibility matter at every stage.</p><p>From individual homes to commercial buildings and specialist rebuilds, we focus on practical solutions and durable results. Clients work with an experienced contractor who sees both the detail on site and the wider project.</p></div></section><section className="values section"><div className="value-stat"><strong>25</strong><span>years of construction and project management</span></div><div className="value-list"><div><span>01</span><h3>Practical expertise</h3><p>Decisions grounded in real building experience.</p></div><div><span>02</span><h3>Clear responsibility</h3><p>Accountable coordination from planning to handover.</p></div><div><span>03</span><h3>Lasting quality</h3><p>Workmanship focused on performance and durability.</p></div></div></section><section className="trust-strip" aria-label="Qualifications and assurance">{standards.map((item) => <div key={item}><span>&#10003;</span>{item}</div>)}</section><ContactBand /><SiteFooter /></main>;
}
