import type { Metadata } from "next";
import Link from "next/link";
import { ContactBand, PageHero, SiteFooter, SiteHeader } from "../site-components";

export const metadata: Metadata = { title: "Project Types | DAASK Build Ltd", description: "Explore the types of domestic, commercial, energy, heritage and specialist construction projects DAASK Build can undertake." };

const types = [
  { id: "domestic", number: "01", title: "Domestic Buildings", lead: "Homes shaped around how people live.", text: "From a new family home to a carefully planned extension or full renovation, DAASK Build coordinates structure, fabric, services and finishes as one complete project.", items: ["New-build homes", "Extensions", "Whole-house renovations", "Energy upgrades", "Internal reconfiguration"], href: "/services/new-builds" },
  { id: "commercial", number: "02", title: "Commercial Buildings", lead: "Practical spaces built for everyday use.", text: "Commercial work demands clear programmes, coordinated trades and minimal uncertainty. We approach each building around its operational requirements, programme and long-term performance.", items: ["New commercial buildings", "Refurbishments", "Fit-out and reconfiguration", "Fabric upgrades", "Project coordination"], href: "/services/project-management" },
  { id: "performance", number: "03", title: "Energy & Passive", lead: "Comfort and efficiency built into the fabric.", text: "High-performance construction relies on careful junctions, continuity and system integration. We coordinate the building envelope and renewable technologies around the intended performance.", items: ["Passive buildings", "Renewable systems", "Insulation and airtightness", "Thermal-detail coordination", "SEAI-related contractor works"], href: "/services/passive-buildings" },
  { id: "specialist", number: "04", title: "Heritage & Specialist", lead: "Complex work handled with informed care.", text: "Traditional fabric, rebuilds and multidisciplinary settings each bring unique constraints. Our role is to understand them early and create a controlled, practical delivery plan.", items: ["Heritage buildings", "Sensitive repair", "MEICA rebuilds", "Multidisciplinary upgrades", "Plant-supported site work"], href: "/services/heritage-buildings" },
];

export default function ProjectTypesPage() {
  return <main><SiteHeader /><PageHero eyebrow="Project types" title="Different buildings. The same disciplined approach." lead="DAASK Build brings construction and project-management experience to domestic, commercial, performance-led and specialist work." /><section className="type-list section">{types.map((type) => <article id={type.id} key={type.id}><div className="type-title"><span>{type.number}</span><p className="eyebrow dark"><i /> Project type</p><h2>{type.title}</h2><strong>{type.lead}</strong></div><div className="type-body"><p>{type.text}</p><ul>{type.items.map((item) => <li key={item}>{item}</li>)}</ul><Link className="button button-outline" href={type.href}>Related service</Link></div></article>)}</section><section className="honest-projects"><div><p className="eyebrow"><span /> Project conversations</p><h2>Have a specific building in mind?</h2></div><p>Every site and brief is different. A direct conversation is the best way to establish whether DAASK Build is the right fit and what information is needed next.</p></section><ContactBand /><SiteFooter /></main>;
}
