import type { Metadata } from "next";
import { ContactBand, PageHero, SiteFooter, SiteHeader } from "../site-components";

export const metadata: Metadata = { title: "How We Work | DAASK Build Ltd", description: "See how DAASK Build takes construction projects from first discussion through planning, delivery and handover." };
const phases = [
  ["01", "Initial discussion", "We start with the outcome you need, the site or building, your preferred timescale and the information already available.", ["Project goals", "Location and access", "Drawings or approvals", "Timescale and priorities"]],
  ["02", "Review & definition", "The scope is clarified so responsibilities, sequencing, specialist input and important decisions are visible before work begins.", ["Scope review", "Buildability", "Trade requirements", "Project constraints"]],
  ["03", "Planning the work", "A practical route to delivery is established around programme, procurement, site setup and communication.", ["Programme", "Materials", "Site arrangements", "Communication points"]],
  ["04", "Construction delivery", "Work is coordinated on site with close attention to workmanship, safety, interfaces and progress.", ["Trade coordination", "Quality checks", "Progress updates", "Issue resolution"]],
  ["05", "Completion & handover", "Details are closed out, the completed work is reviewed and the building is handed over clearly.", ["Final inspection", "Completion items", "Site close-out", "Handover"]],
];
export default function HowWeWorkPage() { return <main><SiteHeader /><PageHero eyebrow="How we work" title="Clarity at every stage." lead="A well-managed construction project keeps decisions, responsibilities and progress visible from the outset." /><section className="phases section"><div className="section-heading"><div><p className="eyebrow dark"><span /> Our process</p><h2>From first conversation to handover.</h2></div><p>The exact route adapts to the project, but these five phases provide a clear working structure.</p></div>{phases.map(([number,title,text,items]) => <article key={number as string}><span>{number as string}</span><div><h3>{title as string}</h3><p>{text as string}</p></div><ul>{(items as string[]).map((item) => <li key={item}>{item}</li>)}</ul></article>)}</section><section className="decision-band"><p className="eyebrow"><span /> Communication</p><h2>Good projects are built on timely decisions.</h2><p>We keep communication practical: what has been completed, what comes next, what needs a decision and where a change affects the wider programme.</p></section><ContactBand /><SiteFooter /></main>; }
